service: kezzle-api-2

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-layers

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  runtime: nodejs16.x
  # ecr:
  #   images:
  #     appimage:
  #       path: ./
  #       platform: linux/amd64
  deploymentBucket:
    name: kezzle-serverless-upload

package:
  individually: true
  exclude:
    - node_modules/**

functions:
  main:
    timeout: 30
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
# functions:
#   main:
#     architecture: x86_64
#     timeout: 30
#     image:
#       name: appimage
#       command:
#         - dist/lambda.handler
#       entryPoint:
#         - '/lambda-entrypoint.sh'
#     # handler: src/lambda.handler
#     events:
#       - http:
#           method: any
#           path: /{any+}
