service: kezzle-api-2

plugins:
  - serverless-offline
  # - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  runtime: nodejs18.x
  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64

# package:
#   individually: true
# exclude:
#   - node_modules/aws-sdk/**

# functions:
#   main:
#     handler: src/lambda.handler
#     events:
#       - http:
#           method: ANY
#           path: '{proxy+}'

functions:
  main:
    architecture: x86_64
    timeout: 30
    image:
      name: appimage
      command:
        - dist/lambda.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    # handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
