# name: Deploy main branch

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: deploy
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x]
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: npm ci
#       - name: Create .env file
#         run: |
#           echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
#           echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> .env
#           echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env
#           echo "MONGODB_DBNAME=${{ secrets.MONGODB_DBNAME }}" >> .env
#           echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
#           echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> .env
#           echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .env
#           echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
#           echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env

#       - name: serverless deploy
#         uses: serverless/github-action@v3.2
#         with:
#           args: deploy
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
